### PR TITLE
Fix header warnings

### PR DESCRIPTION
**Pull request by danthony06**
I fixed a bunch of includes to remove deprecated headers to reduce the number of build warnings.

Distro A, OPSEC #4584

### CODE REVIEW

**Comment by pjreed** [comment]
While these deprecation warnings are very annoying, unfortunately, the new versions of these headers did not exist prior to Foxy.  Until we're ready to drop support for Dashing and Eloquent, I'd rather just deal with warning messages than unnecessarily break compatibility.  Is there any other way to suppress those warnings?

**Comment by danthony06** [comment]
Hmm, I can check into that. I don't suppose we want a separate Foxy branch, do we?

**Comment by pjreed** [comment]
I'd rather not have a separate branch if we could avoid it, since that means every PR would need to be cherry-picked into an additional branch.  It'd actually be nice if we only had a single `master` branch that worked in both ROS1 and ROS2, which is possible, but that would require a ton of conditional compilation stuff that we didn't want to deal with...

**Comment by danthony06** [comment]
Okay, I'll look into other methods of suppressing the warning or another
way of solving it.

**Comment by danthony06** [comment]
Closing this in favor of: https://github.com/swri-robotics/marti_common/pull/621

**Pull request closed without merging**
