### PR TITLE
Add OptionalDiagnosedPublisher class

### PR DESCRIPTION
**Pull request by pjreed**
This is identical to diagnostic_updater::DiagnosedPublisher except that it can be enabled or disabled; when disabled, it will publish an "OK" diagnostic indicating that it has been disabled.

This is useful for when you have a DiagnosedPublisher for a topic in order to monitor its publish rate but it is acceptable for that topic to be turned off so that it's not publishing anything.

### CODE REVIEW

**Comment by pjreed** [comment]
If you want to test this, you can do so against the `6-diagnostics-show-errors-for-unpublished-topics` branch on our internal `microstrain_3dm_gx4` repository.

**Comment by evenator** [comment]
Isn't the `override` specifier C++11 only?

**Comment by pjreed** [comment]
Indeed it is.  Since this is a header-only class, it doesn't actually matter for the compilation of this package, but I suppose it would make sense to remove that since nothing else in this class uses C++11.

**Comment by evenator** [comment]
Yeah, I'd like to avoid `swri_cpp` requiring C++11, especially since it causes problems with PCL.

**Comment by pjreed** [comment]
The status on this branch seems to have timed out for some reason, but the build was successful: https://travis-ci.org/swri-robotics/marti_common/builds/269656297

**Pull request merged**
