### PR TITLE
Fixed compile error when ros-indigo-opencv3 is installed

### PR DESCRIPTION
**Pull request by kimmat**
I was unable to compile the marti_common when ros-indigo-opencv3 was installed. This patch fixed the issue.

### CODE REVIEW

**Comment by pjreed** [comment]
Good catch.  I've noticed that swri_image_util, swri_opencv_util, and swri_transform_util also all depend on OpenCV 2 but do not specify the version number; could you add those to your pull request?

**Comment by kimmat** [comment]
I updated the CMakeFiles.txt. It would be great if you could merge it into your repository.

**Comment by evenator** [comment]
LGTM. @pjreed, should we add a Travis test for this?

**Comment by pjreed** [comment]
Yeah, probably.  The easiest way to test it would probably be to just manually install the ros-indigo-opencv3 packge before compling; it's very obvious when it fails.

**Pull request merged**
