### PR TITLE
Check for error from ioctl in serial_port

### LINKED ISSUE #406: swri_serial_util segfaults on error
Line 307 of swri_serial_util/src/serial_port.cpp gets the number of available bytes using `iotctl( .. )`. On failure, this outputs -1 bytes to read. This is subsequently static cast to `size_t`, yielding 18446744071897977696 bytes to read. The program then tries to allocate that many bytes on line 312 and runs out of memory.

### PR DESCRIPTION
**Pull request by evenator**
Fixes #406

### CODE REVIEW

**Comment by malban** [comment]
Can you squash this into 1 commit?

**Comment by elliotjo** [comment]
I recommend adding more information to the error message to help figure out why the call fails:

error_msg_ = std::string("Error getting number of available bytes from serial port (") + strerror(errno) + ")";

**Comment by evenator** [comment]
@malban I was planning to squash on merge.
@elliotjo  Yeah, I can make that change.

**Comment by evenator** [comment]
Updated with @elliotjo's suggestion and squashed per @malban's request

**Pull request merged**
