### PR TITLE
Fixing build status buttons (Jade version)

### PR DESCRIPTION
**Pull request by pjreed**
The ROS build farm has moved to a new server, and all of the button URLs
have been changed to point to the new server.

### CODE REVIEW

**Comment by pjreed** [comment]
It looks like the Jade branch is failing to build due to swri_geometry_util (and possibly others) being unable to find "Eigen3".  That should be fixed, but it's not related to this pull request.

**Comment by evenator** [comment]
What are the travis CI changes?

**Comment by evenator** [comment]
also, I ticketed the build failure issue in #296

**Comment by pjreed** [comment]
The previous .travis.yml file was based on a template that did both Indigo and Jade builds and allowed the build to pass even if the Jade build failed; the Indigo part of the template had been removed, but the bit that allowed the build to pass even if it actually failed had not.

**Comment by evenator** [comment]
Let me see if I can get #296 fixed

**Comment by pjreed** [comment]
I'm not sure why this is still failing, as this branch builds just fine for me when I run it in my own docker container.  Maybe something is failing to update on the Travis CI side because this branch was based on a branch that didn't build or have a .travis.yml file at the time it was created?  I'll try a few other things, and then I might just go ahead and merge this into jade-devel and fix it in another branch if it's still broken.

**Comment by evenator** [comment]
In any case, this PR doesn't introduce a regression. LGTM.

**Pull request merged**
