### PR TITLE
Create warp_image Nodelet

### LINKED ISSUE #445: swri_image_util: A Nodelet to Perform Arbitary Perspective Transforms
I need a nodelet that can apply an arbitrary perspective transformation, specified by a 3x3 transformation matrix. This is similar to what [image_proc/rectify](https://wiki.ros.org/image_proc#image_proc.2BAC8-diamondback.image_proc.2BAC8-rectify) does, but image_proce/rectify only works on calibrated cameras (if the k matrix is not filled, it refuses to process images, and if the distortion vector is not filled, it passes through images unchanged).

This node should take in a 3x3 transformation matrix as a parameter, a list of 9 floats, apply that transform to an incoming image using OpenCV, and publish the resulting image. There may be other parameters for cropping and interpolation options.

### PR DESCRIPTION
**Pull request by evenator**
Add a nodelet to swri_image util that applies a 3x3 transformation
matrix to an image using cv::warpPerspective and publishes the
resulting image.

closes #445

### CODE REVIEW

**Comment by evenator** [comment]
The majority of the changes here are from alphabetizing things in the CMakeLists.txt and nodelet_plugins.xml.

**Comment by jatowler** [comment]
This nodelet always warps the image into an image of the same size as the input; this is not necessarily always desirable. Use case: warping an image into a metric space with a known px/m resolution. I suggest nodelet parameters to optionally provide output resolution.

**Comment by evenator** [comment]
I tested this node, and it worked as expected. This PR is ready to merge. Does anyone have any final notes or requests?

**Comment by evenator** [comment]
I'm planning to hold this MR until #443 gets merged.

**Comment by evenator** [comment]
Rebased onto indigo-devel now that #443 is merged.

**Comment by evenator** [comment]
Now that the branch unification is complete, this is ready to merge.

**Pull request merged**
