### PR TITLE
stamp local_xy_origin message picked from list with now()

### PR DESCRIPTION
**Pull request by daniel-dsouza**

### CODE REVIEW

**Comment by pjreed** [comment]
LGTM; do you know if this is also an issue for the ROS2 version in the `dashing-devel` branch?  If so, could you cherry-pick this over there?

**Comment by daniel-dsouza** [comment]
> LGTM; do you know if this is also an issue for the ROS2 version in the `dashing-devel` branch? If so, could you cherry-pick this over there?

no idea. Currently don't have an environment for ROS2 setup.

**Comment by matt-attack** [comment]
> > LGTM; do you know if this is also an issue for the ROS2 version in the `dashing-devel` branch? If so, could you cherry-pick this over there?
> 
> no idea. Currently don't have an environment for ROS2 setup.

You should be able to just cherry-pick it onto it without trying to test or build it.

**Comment by daniel-dsouza** [comment]
> > > LGTM; do you know if this is also an issue for the ROS2 version in the `dashing-devel` branch? If so, could you cherry-pick this over there?
> > 
> > 
> > no idea. Currently don't have an environment for ROS2 setup.
> 
> You should be able to just cherry-pick it onto it without trying to test or build it.

Don't think we have an `origin_manager.py` for ros2

**Pull request merged**
